name: Build and run Maestro tests (Native Android)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # 2. Prepare Maestro Workspace
      # The Maestro Cloud Action expects flow files to be inside the .maestro/ directory.
      - name: Prepare Maestro Workspace
        run: |
          echo "Creating .maestro/ directory and copying flow file..."
          # Create the required default workspace directory
          mkdir -p .maestro
          # Copy the flow file from 'samples/' into the workspace
          cp samples/android-test.yaml .maestro/
          # Optional: List contents to confirm
          ls -R .maestro
          
      # 3. Run Maestro Tests on Maestro Cloud
      # The action automatically uploads test files from the .maestro/ workspace.
      - name: Run Maestro Tests on Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          # Your API Key, which must be stored securely as a repository secret (secrets.MAESTRO_API_KEY)
          api-key: ${{ secrets.MAESTRO_API_KEY }} 
          # Your Project ID
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }} 
          # Path to the pre-committed APK
          app-file: samples/wikipedia.apk 
          # The workspace is automatically determined as .maestro/
          # Removed unsupported 'flow-file' parameter: The test action automatically finds it in .maestro/
          # Add any other parameters here, like tags or environments
      # 4. Reporting Information (Informational Step)
      - name: View Detailed Test Reports
        run: |
          echo "--------------------------------------------------------"
          echo "Maestro test run is complete!"
          echo "All comprehensive test results, including detailed execution steps, video recordings, and screenshots for every test, are available at the Maestro Cloud Dashboard:"
          echo "https://app.maestro.dev/"
          echo "--------------------------------------------------------"
