name: Build and run Maestro tests (Native Android)

on:
  # Run tests whenever code is pushed to main or a Pull Request is opened
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Set up Java 17 (Adhering to your original requested version for the build process)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Run Maestro Tests on Maestro Cloud
      # This action now uses pre-committed files (samples/wikipedia.apk and samples/android-test.yaml),
      # effectively running the command: maestro cloud --api-key=... samples/wikipedia.apk samples/android-test.yaml
      - name: Run Maestro Tests on Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          # Your API Key, which must be stored securely as a repository secret (secrets.MAESTRO_API_KEY)
          api-key: ${{ secrets.MAESTRO_API_KEY }} 
          # Your Project ID
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }} 
          # Path to the pre-committed APK
          app-file: samples/wikipedia.apk 
          # Path to your Maestro flow file
          flow-file: samples/android-test.yaml
          # Add any other parameters here, like tags or environments
