name: Maestro Android E2E Test on Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  maestro_e2e_android:
    runs-on: macos-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Maestro CLI via Homebrew
      run: |
        brew tap mobile-dev-inc/tap
        brew install maestro
        export PATH="$PATH:$HOME/.maestro/bin"

    - name: Run Android Emulator and Maestro Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        # 🔥 FIX: Switched to API 33 (Android 13) to avoid the 
        # "failed to initialize HVF: Invalid argument" error often seen with API 30 on ARM runners.
        api-level: 33 
        target: google_apis 
        profile: Nexus 5
        arch: arm64-v8a 
        
        script: |
          # 1. Install the APK
          APK_PATH="./samples/wikipedia.apk" 
          echo "Installing $APK_PATH on emulator (API 33)..."
          adb install $APK_PATH
          
          # 2. Run the specified Maestro flow and generate the JUnit report
          MAESTRO_REPORT_PATH="maestro-report.xml"
          MAESTRO_FLOW_PATH="./samples/android-test.yaml"
          
          echo "Running Maestro flow: $MAESTRO_FLOW_PATH"
          
          maestro test \
            $MAESTRO_FLOW_PATH \
            --format junit \
            --output $MAESTRO_REPORT_PATH \
            || true 
          
          # 3. Prepare report for artifact upload
          mkdir -p maestro-reports
          if [ -f $MAESTRO_REPORT_PATH ]; then
            mv $MAESTRO_REPORT_PATH maestro-reports/
            echo "Maestro test run complete. Report moved to maestro-reports/."
          else
            echo "Warning: Maestro report file ($MAESTRO_REPORT_PATH) not found. Check the Maestro run logs."
          fi

    - name: Upload Test Report Artifact
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: maestro-junit-report
        path: maestro-reports/maestro-report.xml
