name: Build and run Maestro tests (Native Android)

on:
  # Run tests whenever code is pushed to main or a Pull Request is opened
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-cloud-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Set up Java 17 (Adhering to your original requested version for the build process)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # 2. Prepare Maestro Workspace
      # The Maestro Cloud Action expects flow files to be inside the .maestro/ directory.
      - name: Prepare Maestro Workspace
        run: |
          echo "Creating .maestro/ directory and copying flow file..."
          # Create the required default workspace directory
          mkdir -p .maestro
          # Copy the flow file from 'samples/' into the workspace
          cp samples/android-test.yaml .maestro/
          # Optional: List contents to confirm
          ls -R .maestro
          
      # 3. Run Maestro Tests on Maestro Cloud
      # Removed the unsupported 'flow-file' parameter. The action will now automatically 
      # find and run the 'android-test.yaml' file inside the '.maestro/' workspace.
      - name: Run Maestro Tests on Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          # Your API Key, which must be stored securely as a repository secret (secrets.MAESTRO_API_KEY)
          api-key: ${{ secrets.MAESTRO_API_KEY }} 
          # Your Project ID
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }} 
          # Path to the pre-committed APK
          app-file: samples/wikipedia.apk 
          # The workspace is automatically determined as .maestro/
          # Path to your Maestro flow file
          flow-file: samples/android-test.yaml
